### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#35] opened 2019-01-31 08:04 UTC
Hello,
Is it possible to add drag and drop support (searching a way to not use tkinter :D) ?

**Comment by fourminute** [comment] 2019-01-31 10:20
Yes very possible. I may include it in the next major release after the localisations have been merged.

**Comment by Gee19** [comment] 2019-03-25 01:05
Was messing around a bit with this today, looks like Tk support for drag and drop isn't great. (https://github.com/python/cpython/blob/master/Lib/tkinter/dnd.py)

fcd32a8cdfc5aa67153dbb22493a6d6c199b35d2

Some random resources I was looking at:
https://stackoverflow.com/questions/4151637/pyqt4-drag-and-drop-files-into-qlistwidget
https://www.reddit.com/r/learnpython/comments/97z5dq/pyqt5_drag_and_drop_file_option/
http://zetcode.com/gui/pyqt5/dragdrop/

**Comment by fourminute** [comment] 2019-04-05 08:17
I have tried many different types of Drag N Drop all seemed to be completely terrible by design. Hopeful but not optimistic lol.

**Closed** 2023-08-21 22:21 UTC
Labels: enhancement, awaiting assignment
